default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: beer-tournament_development

test:
  <<: *default
  database: beer-tournament_test

production:
  <<: *default
  database: beer-tournament_production
  username: beer-tournament
  password: <%= ENV['BEER-TOURNAMENT_DATABASE_PASSWORD'] %>
